trigger:
- none
 
variables:
  IISWebsiteName: 'burgazli'
 
resources:
  pipelines:
  - pipeline: 'buildPipeline'
    project: 'burgazli'
    source: 'Build pipeline'
    branch: 'main'   
 
stages:
  - stage: DeployWebsite
    displayName: 'Deploy website'       
    pool:
      vmImage: windows-latest
     
    jobs:   
    - deployment: DeployWebsite
      displayName: 'Deploy website'
      environment: 'Windows 11 server.WIN-TTCB83P9FR6'
      strategy:
       runOnce:
         deploy:          
          steps:
          - checkout: none
           
          - download: 'buildPipeline'
            name: 'DownloadBuildArtifacts'           
            displayName: 'Download build artifacts'
            artifact: 'burgazli'
                     
          - task: IISWebAppManagementOnMachineGroup@0
            name: 'StopIIS'
            displayName: 'Stop IIS website - ${{ variables.IISWebsiteName }}'
            inputs:
              IISDeploymentType: 'IISWebsite'
              ActionIISWebsite: 'StopWebsite'
              StartStopWebsiteName: '${{ variables.IISWebsiteName }}'         
                           
          - task: IISWebAppDeploymentOnMachineGroup@0
            name: 'DeployIIS'
            displayName: 'Deploy IIS website - ${{ variables.IISWebsiteName }}'         
            inputs:
              WebSiteName: '${{ variables.IISWebsiteName }}'             
              Package: '$(Pipeline.Workspace)\buildPipeline\burgazli\emirburgazli.AzureTestProject'
              TakeAppOfflineFlag: true
           
          - task: IISWebAppManagementOnMachineGroup@0
            name: 'StartIIS'
            displayName: 'Start IIS website - ${{ variables.IISWebsiteName }}'               
            inputs:
              IISDeploymentType: 'IISWebsite'
              ActionIISWebsite: 'StartWebsite'
              StartStopWebsiteName: '${{ variables.IISWebsiteName }}'